export const memberSignupButtonQuotes = [
  "“Ray, if someone asks you if you're a god, you say YES!”",
  "“Leave the gun. Take the cannolli.”",
  "“Of course I'm serious. And don't call me Shirley.”",
  "“You'll shoot your eye out kid.”",
  "“Louis, I think this is the beginning of a beautiful freindhsip.”",
  "“I'll have what she's having.”",
  "“I'm mad as hell and I'm not going to take it anymore.”",
  "“Nobody puts Baby in a corner.”",
  "“The Dude abides.”",
  "“Have fun storming the castle.”",
  "“That rug really tied the room together, did it not?”",
  "“Let's not bicker and argue over who killed who.”",
  "“Gentlemen, you can't fight in here! This is the war room.”",
  "“You had me at Hello.”",
  "“There's no crying in baseball!”",
  "“Demented and sad, but social.”",
  "“Great success!”",
  "“Guess you broke into the wrong goddamned rec room didn't ya!”",
  "“I am a loner Dottie, a rebel.”",
  "“That'll do Pig. That'll do.”",
  "“Screws fall out all the time. The world's an imperfect place.”",
  "“Strange things are afoot at the Circle K.”",
  "“Of course I'm serious, and don't call me Shirley.”",
  "“Ho, Ho, Ho, Now I have a machine gun too.”",
  "“Not unless you find circular to be particularly funny.”",
  "“I'm here to kick butt and chew bubblegum...and I'm all out of bubblegum.”",
  "“Hello. My name is Inigo Montoya. You killed my father. Prepare to die.”",
  "“You're gonna need a bigger boat.”",
  "“What we've got here is a failure to communicate. Which is the way he wants it.”",
  "“Cinderella story. Outta nowhere. A former greenskeeper. It's a mirac... It's in the hole! It's in the hole!”",
  "“Frankly my dear, I don't give a damn.”",
  "“Go ahead, make my day.”",
  "“A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.”",
  "“You can't handle the truth!”",
  "“I want to be alone.”",
  "“Mama always said that life is like a box of chocolates, you never know what you are gonna get.”",
  "“Houston, we have a problem.”",
  "“Life moves pretty fast. If you dont stop and look around once in a while, you could miss it.”",
  "“Carpe Diem. Seize the day boys. Make your lives extraordinairy.”",
  "“Inconceivable!!”",
  "“Allright Mr. Demille. I'm ready for my closeup.“",
  "“I'm sorry Dave. I'm afraid I can't do that.”",
  "“The first rule of fight club is you do not talk about fight club.”",
  "“Are you not entertained?”",
  "“I was told that I could listen to the radio at a reasonable volume from nine to eleven.“",
];
