export const memberSignupButtonQuotes = [
  "“Ray, if someone asks you if you're a god, you say YES! And then you click this button right here and become a member!”",
  "“Leave the gun. Take the cannoli. Become a member.”",
  "“You're gonna need a bigger boat. Or at the very least, you're gonna need to become a member.”",
  "“What we've got here is a failure to communicate. Which is why you're gonna need to become a member today.”",
  "“Cinderella story. Outta nowhere. A former greenskeeper, now a member. It's a mirac... It's in the hole! It's in the hole!”",
  "“You had me at 'I'm already a member'”",
  "“Frankly my dear, if you haven't already become a member, I don't give a damn”",
  "“Go ahead, make my day. Become a member.”",
  "“A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti. He was not a member.”",
  "“You can't handle the truth! Well not yet, but you will be able to if you become a member today.”",
  "“I want to be alone, so I can click this button and become a member today.”",
  "“Mama always said that life is like a box of chocolates, you never know what you are gonna get. But if you become a member, you will.”",
  "“Houston, we have a problem. But I'm pretty sure you can fix it by becoming a member today. ”",
  "“Life moves pretty fast. If you dont stop and look around once in a while, or at least become a member, you could miss it.”",
  "“Carpe Diem. Sieze the day boys. Make your lives extraordinairy. Become a member before time runs out.”",
  "“You haven't become a member yet? Inconceivable!!”",
  "“Allright Mr. Demille. I'm a member now. I'm ready for my closeup.“",
  "“I'm sorry Dave. I'm afraid I can't do that. But I can make you a member today if you'd like.”",
  "“The first rule of fight club is you do not talk about fight club. Become a member today.”",
  "“Are you not entertained? Will you not become a member today?”",
  "I was told that because I'm a member I could listen to the radio at a reasonable volume from nine to eleven.",
];
