export const memberSignupButtonQuotes = [
  "“Ray, if someone asks you if you're a god, you say YES!”",
  "“Leave the gun. Take the cannoli.”",
  "“You're gonna need a bigger boat.",
  "“What we've got here is a failure to communicate. Which is the way he wants it.”",
  "“Cinderella story. Outta nowhere. A former greenskeeper. It's a mirac... It's in the hole! It's in the hole!”",
  "“You had me at hello”",
  "“Frankly my dear, I don't give a damn”",
  "“Go ahead, make my day.”",
  "“A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.”",
  "“You can't handle the truth!”",
  "“I want to be alone.”",
  "“Mama always said that life is like a box of chocolates, you never know what you are gonna get.”",
  "“Houston, we have a problem.”",
  "“Life moves pretty fast. If you dont stop and look around once in a while, you could miss it.”",
  "“Carpe Diem. Seize the day boys. Make your lives extraordinairy.”",
  "“Inconceivable!!”",
  "“Allright Mr. Demille. I'm ready for my closeup.“",
  "“I'm sorry Dave. I'm afraid I can't do that.”",
  "“The first rule of fight club is you do not talk about fight club.”",
  "“Are you not entertained?”",
  "“I was told that I could listen to the radio at a reasonable volume from nine to eleven.“",
];
