site_url: https://theop-io-static.netlify.app

backend:
  name: github # Require a GitHub account
  repo: theop-io/theop-io-static
  branch: main

media_folder: "src/uploads" # Shouldn't use this but it's required, so sure. Relative to the repository root.
public_folder: "/uploads"

collections:
  - name: "the-shots" # Used in routes
    label: "The Shots" # Used in the admin UI
    label_singular: "Shot" # ...same
    folder: "src/the-shots/data" # Relative to repository root
    format: "json" # Store in JSON
    create: true # Allow new documents to be created
    slug: "{{shotId}}"
    path: "{{year}}/{{slug}}"
    identifier_field: "shotId"
    fields:
      - label: "Shot Identifier" # Needs to be unique
        name: "shotId"
        widget: "string"
        hint: "Needs to be unique across all shots in the database"

      # Production info
      - label: "Production Name"
        name: "production"
        widget: "string"
      - label: "Production Year"
        name: "year"
        widget: "number"
        default: 2024
        value_type: int
        min: 1920
        max: 2030
      - label: "Episode"
        name: "episode"
        widget: "string"
        required: false

      # Operator info
      - label: "Operator"
        name: "operator"
        widget: "object"
        summary: "{{fields.operatorName}}"
        fields:
          - label: "Operator Name"
            name: "operatorName"
            widget: "string"
          - label: "Alternative Operator Name"
            name: "altOperatorName"
            widget: "string"
            required: false

      # Content
      - label: "Short Description"
        name: "shortDescription"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"

      # Optional additional content
      - label: "Operator Comments"
        name: "operatorComments"
        widget: "text"
        required: false
      - label: "Equipment"
        name: "equipment"
        widget: "text"
        required: false

  - name: "lists"
    label: "Lists"
    files:
      - name: "the-shots-file" # Used in routes
        label: "The Shots (As File)" # Used in the admin UI
        label_singular: "Shot" # ...same
        file: "src/the-shots/the-shots-data.json" # Relative to repository root
        format: "json" # Store in JSON
        identifier_field: "shotId"
        fields:
          - label: "Shot Identifier" # Needs to be unique
            name: "shotId"
            widget: "string"
            hint: "Needs to be unique across all shots in the database"

          # Production info
          - label: "Production Name"
            name: "production"
            widget: "string"
          - label: "Production Year"
            name: "year"
            widget: "number"
            default: 2024
            value_type: int
            min: 1920
            max: 2030
          - label: "Episode"
            name: "episode"
            widget: "string"
            required: false

          # Operator info
          - label: "Operator"
            name: "operator"
            widget: "object"
            summary: "{{fields.operatorName}}"
            fields:
              - label: "Operator Name"
                name: "operatorName"
                widget: "string"
              - label: "Alternative Operator Name"
                name: "altOperatorName"
                widget: "string"
                required: false

          # Content
          - label: "Short Description"
            name: "shortDescription"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"

          # Optional additional content
          - label: "Operator Comments"
            name: "operatorComments"
            widget: "text"
            required: false
          - label: "Equipment"
            name: "equipment"
            widget: "text"
            required: false
