site_url: https://theop-io-static.netlify.app

backend:
  name: github # Require a GitHub account
  repo: theop-io/theop-io-static
  branch: main

media_folder: "src/uploads" # Shouldn't use this but it's required, so sure. Relative to the repository root.
public_folder: "/uploads"

collections:
  - name: "the-shots" # Used in routes
    label: "The Shot Productions" # Used in the admin UI
    label_singular: "Production" # ...same
    folder: "src/the-shots/data" # Relative to repository root
    format: "json" # Store in JSON
    create: true # Allow new documents to be created
    editor:
      preview: false # Our previews are useless/non-existent so just suppress them
    slug: "{{productionName}}"
    identifier_field: "productionName"
    fields:
      - name: "productionName"
        label: "Production Name and Year" # Needs to be unique; hopefully including the year makes it so.
        hint: "e.g. 'The Abyss (1989)'"
        widget: "string"
        pattern:
          [
            '.+\(\d{4}\)',
            "Needs to include four-digit year in parentheses, e.g. 'The Abyss (1989)'",
          ]

      # Operator info
      - name: "operator"
        label: "Operator"
        widget: "object"
        summary: "{{fields.operatorName}}"
        fields:
          - name: "operatorName"
            label: "Operator Name"
            widget: "string"
          - name: "secondaryOperatorName"
            label: "Secondary Operator Name"
            widget: "string"
            required: false

      # List of shots
      - name: "shots"
        label: "Shots"
        label_singular: "Shot"
        widget: "list"
        summary: "{{fields.timestamp}}: {{fields.shortDescription}}"
        fields:
          - name: "timestamp"
            label: "Timestamp"
            widget: "string"
            hint: "e.g. '12:45' for 12 minutes 45 seconds in, or '1:45:00' for one hour and 45 minutes in"
            pattern: ['^\d+:(?:\d{2}:)?\d{2}$', "Provide timestamp as min:sec or hour:min:sec"]

          # Content
          - name: "shortDescription"
            label: "Short Description"
            widget: "string"
          - name: "description"
            label: "Description"
            widget: "text"

          # Optional additional content
          - name: "operatorComments"
            label: "Operator Comments"
            widget: "text"
            required: false
          - name: "equipment"
            label: "Equipment"
            widget: "text"
            required: false
