site_url: https://theop-io-static.netlify.app

backend:
  name: github # Require a GitHub account
  repo: theop-io/theop-io-static
  branch: main

media_folder: "src/uploads" # Shouldn't use this but it's required, so sure. Relative to the repository root.
public_folder: "/uploads"

collections:
  - name: "tags" # Used in routes
    # How it's presented in the admin UI
    label: "Tags"
    label_singular: "Tag"
    editor:
      preview: false # Our previews are useless/non-existent so just suppress them

    files:
      - name: "shot-tags"
        # How it's presented in the admin UI
        label: "Shot Tags"

        # How it's stored
        file: "src/the-shots/data/the-shots-tags.json"
        format: "json"

        # Fields
        fields:
          - name: "shot-tags"
            label: "Tags"
            label_singular: "Tag"
            description: "List of shot tags"
            widget: "list"
            fields:
              - name: "shot-tag"
                label: "Shot tag"
                widget: "string"

  - name: "the-shots" # Used in routes
    # How it's presented in the admin UI
    label: "The Shots"
    label_singular: "Production"
    summary: "{{productionName}} [{{status}}]"
    editor:
      preview: false # Our previews are useless/non-existent so just suppress them

    sortable_fields: ["productionName", "operatorName", "status"]

    view_groups:
      - label: Operator
        field: operatorName
      - label: Published vs. Draft
        field: status

    # How it's stored
    folder: "src/the-shots/data/shots" # Relative to repository root
    format: "json" # Store in JSON
    create: true # Allow new documents to be created
    slug: "{{productionName}}"

    # How it's indexed
    identifier_field: "productionName"

    # Fields
    # - NOTE: Keep these in sync with /tools/the-shots-build-tools.ts
    fields:
      - name: "productionName"
        label: "Production Name/Year" # Needs to be unique; hopefully including the year makes it so.
        hint: "e.g. 'The Abyss (1989)'"
        widget: "string"
        pattern:
          [
            '.+\(\d{4}\)',
            "Needs to include four-digit year in parentheses, e.g. 'The Abyss (1989)'",
          ]

      - name: "status"
        label: "Status"
        widget: "select"
        options:
          - label: "Published"
            value: "published"
          - label: "Draft"
            value: "draft"
        default: "published"
        multiple: false

      # List of shots
      - name: "shots"
        label: "Shots"
        label_singular: "Shot"
        widget: "list"
        summary: "{{fields.shortDescription}}"
        fields:
          # Operator info
          - name: "operatorName"
            label: "Operator Name"
            widget: "string"
          - name: "secondaryOperatorName"
            label: "Secondary Operator Name"
            widget: "string"
            required: false

          # Optional metadata
          - name: "timestamp"
            label: "Timestamp"
            widget: "string"
            hint: "e.g. '12:45' for 12 minutes 45 seconds in, or '1:45:00' for one hour and 45 minutes in"
            pattern: ['^\d+:(?:\d{2}:)?\d{2}$', "Provide timestamp as min:sec or hour:min:sec"]
            required: false

          - name: "episode"
            label: "Episode"
            widget: "string"
            required: false

          - name: "link"
            label: "Link to video"
            widget: "string"
            pattern:
              ['^https:\/\/vimeo.com\/\d+', "Please provide a URL like 'https://vimeo.com/...'"]
            required: false

          - name: "tags"
            label: "Tags"
            widget: "relation"
            required: false

            # What we're referencing from
            collection: "tags"
            file: "shot-tags"

            # What value we're referencing
            value_field: "shot-tags.*.shot-tag"
            search_fields: ["shot-tags.*.shot-tag"]

            # How we're allowing ourselves to reference
            multiple: true
            min: 0

          # Content
          - name: "shortDescription"
            label: "Short Description"
            widget: "string"
          - name: "description"
            label: "Description"
            widget: "text"

          # Optional additional content
          - name: "operatorComments"
            label: "Operator Comments"
            widget: "text"
            required: false
          - name: "equipment"
            label: "Equipment"
            widget: "text"
            required: false
