name: JavaScript (NPM) CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js default version
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - run: npm install-clean
    - run: npm run build
